djangoProjectQueueTS/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('queue_app/', include('queue_app.urls')),
    path('', admin.site.urls),
]

queue_app/urls.py
from django.urls import path
from .views import pages, screen, ticket, about, operator, registration, probe


app_name = 'queue_app'
urlpatterns = [
    path('', screen, name='screen'),
    path('pages/', pages, name='pages'),
    path('ticket/', ticket, name='ticket'),
    path('registration/', registration, name='registration'),
    path('operator/', operator, name='operator'),
    path('about/', about, name='about'),
    path('probe/', probe, name='probe'),
   ]

queue_app/models.py
from django.db import models
from datetime import datetime


# Create your models here.
class QueueTab(models.Model):
    data_reg = models.DateField('Дата регистрации', default=datetime.now)
    time_reg = models.TimeField('Время регистрации', default=datetime.now)
    ticket = models.CharField('Номер талона', max_length=200)
    invited = models.DateTimeField('Клиент приглашён', null=True)
    serviced = models.DateTimeField('Обслуживание завершено', null=True)

queue_app/forms.py
from django import forms
from .models import *


class OperatorsForm(forms.ModelForm):
    class Meta:
        model = QueueTab
        fields = ['ticket', 'id']


class RegistrationForm(forms.ModelForm):
    class Meta:
        model = QueueTab
        # labels = ['ticket']
        fields = ['ticket']
        widgets = {'ticket': forms.HiddenInput()}



queue_app/views.py
from datetime import date
from django.shortcuts import render
from django.shortcuts import redirect
from .forms import *
from .models import QueueTab
import socket


gong_was = 0
invited_was = 0


def registration(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            today_reg = date.today()
            wu = QueueTab.objects.latest('id')
            wz = int(wu.ticket)
            wd = wu.data_reg
            # Проверка соответствует ли номер талона интервалу от 1 до 9.
            if (1 > wz) or (wz > 98) or (wd < today_reg):
                wc = 0
            else:
                wc = wz
            wa = wc + 1
            QueueTab.objects.create(ticket=wa)
            return redirect('queue_app:ticket')
    else:
        form = RegistrationForm(initial={'ticket': 11})
    return render(request, 'queue_app/registration.html', {'form': form})


def pages(request):
    return render(request, 'queue_app/pages.html')


def probe(request):
    return render(request, 'queue_app/probe.html')


def screen(request):
    global gong_was
    today_screen = date.today()
    gong = 0
    list_for_screen = QueueTab.objects.filter(serviced__isnull=True, data_reg=today_screen)[:7]
    list_for_screen_count = QueueTab.objects.filter(serviced__isnull=True, data_reg=today_screen)[:7].count()
    invited_on_screen_count = QueueTab.objects.filter(invited__isnull=False, serviced__isnull=True,
                                                      data_reg=today_screen).count()

    opacity_on_screen = 170 + ((list_for_screen_count - 1) * 102)

    if invited_on_screen_count > 0:
        invited_on_screen = 'Пройдите'
        invited_on_screen2 = 'на прием'
    else:
        invited_on_screen = ''
        invited_on_screen2 = ''

    # Cделаем чтобы гонг звучал при вызове только один раз

    if invited_on_screen_count == 0:
        gong_was = 0

    if invited_on_screen_count > 0 and gong_was == 1:
        gong = 0

    if invited_on_screen_count > 0 and gong_was == 0:
        gong_was = 1
        gong = 1

    return render(request, 'queue_app/screen.html', {'list_for_screen': list_for_screen,
                                                     'invited_on_screen': invited_on_screen,
                                                     'invited_on_screen2': invited_on_screen2,
                                                     'gong': gong,
                                                     'opacity_on_screen': opacity_on_screen})


def ticket(request):
    posts = QueueTab.objects.latest('id')
    return render(request, 'queue_app/ticket.html', {'posts': posts})


def about(request):
    return render(request, 'queue_app/about.html')


def operator(request):
    global invited_was
    date_today = date.today()
    dt_today = datetime.today()
    if 'button_invited' in request.POST:
        button_invited_count = QueueTab.objects.filter(invited__isnull=True,
                                                       serviced__isnull=True, data_reg=date_today).count()
        if button_invited_count > 0 and invited_was == 0:
            button_invited_pk = QueueTab.objects.filter(invited__isnull=True,
                                                        serviced__isnull=True, data_reg=date_today).first().pk
            QueueTab.objects.filter(pk=button_invited_pk).update(invited=dt_today)
            invited_was = 1
        return redirect('queue_app:operator')
    elif 'button_serviced' in request.POST:
        button_serviced_count = QueueTab.objects.filter(invited__isnull=False,
                                                        serviced__isnull=True, data_reg=date_today).count()
        if button_serviced_count > 0: # and invited_was == 1:
            button_serviced_pk = QueueTab.objects.filter(invited__isnull=False,
                                                         serviced__isnull=True, data_reg=date_today).first().pk
            QueueTab.objects.filter(pk=button_serviced_pk).update(serviced=dt_today)
            invited_was = 0
        return redirect('queue_app:operator')
    else:
        form = RegistrationForm()

        total_tickets = QueueTab.objects.filter(invited__isnull=True, serviced__isnull=True,
                                                data_reg=date_today).count()

        invited_count = QueueTab.objects.filter(invited__isnull=False, serviced__isnull=True,
                                                data_reg=date_today).count()
        if invited_count > 0:
            invited_ticket = QueueTab.objects.filter(invited__isnull=False, serviced__isnull=True,
                                                     data_reg=date_today).first().ticket
        else:
            invited_ticket = ' - '

        if total_tickets == 0:
            total_tickets = '0'

        return render(request, 'queue_app/operator.html', {'form': form,
                                                           'invited_ticket': invited_ticket,
                                                           'total_tickets': total_tickets})

queue_app/templates/queue_app/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>О проекте</title>
</head>
<body>
<p>О проекте:</p>

    <p>Cистема управления очередью<br>
    Версия 0,5 для малого бизнеса<br>
    Функционал минимальный: одна кнопка регистрации, одноразрядный номер талона 1-9,
        одно окно,9 строк на главном экране.)</p>

    <p>Created 2024 by RodX<br>
    RodX Labs Inc.</p>
</body>
</html>

queue_app/templates/queue_app/operator.html
<!DOCTYPE html>
<html lang="ru">
<head>
    {% load static %}
    <link type="text/css" href="{% static 'queue_app/css/styles.css' %}" rel="stylesheet" />
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    </head>
<body>
<form action="{% url 'queue_app:operator' %}" method="post" >
    {% csrf_token %}
    <div class="operator-container">
        <div class="shape">
            <div class="heading">Оператор СУО QueueTS</div>
            <div class="row">
              <div class="operator-label">В очереди {{total_tickets}} посетителей</div>
                <div class="operator-div-button"><button class="operator-button" name="button_invited">Пригласить посетителя</button></div>
            </div>
            <div class="row">
                <div class="operator-label">Приглашен посетитель с талоном {{invited_ticket}}</div>
                <div class="operator-div-button"><button class="operator-button" name="button_serviced">Работать с посетителем</button></div>
                <div class="operator-end"></div>
            </div>
        </div>
    </div>
</form>
</body>
</html>

queue_app/templates/queue_app/pages.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link type="text/css" href="{% static 'queue_app/css/styles.css' %}" rel="stylesheet" />
     <!-- INCLUDE CSS -->
    <style type="text/css">
    .left
    {
        float: left;
        margin-left: 50px;
    }

    .right
    {
        float: right;
        margin-right: 50px;
    }
    #content
    {
    }
    </style>
</head>
<body><br>
    <div id="content">
        <div class="left">

            Все страницы<br><br>

            <a href="{% url 'queue_app:pages' %}">Все страицы</a><br>
            <a href="{% url 'queue_app:screen' %}">Главный экран</a><br>
            <a href="{% url 'queue_app:registration' %}">Регистрация</a><br>
            <a href="{% url 'queue_app:ticket' %}">Талон последней регистрации</a><br>
            <a href="{% url 'queue_app:operator' %}">Оператор</a><br>
            <a href="/">Менеджер</a><br>
            <a href="{% url 'queue_app:about' %}">О проекте</a><br>
        </div>
    </div>
</body>
</html>

queue_app/templates/queue_app/probe.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Probe</title>
    <link type="text/css" href="{% static 'queue_app/css/styles.css' %}" rel="stylesheet" />
</head>
<body>
<form action="{% url 'queue_app:operator' %}" method="post">
     {% csrf_token %}
    <div class="operator-container">
        <div class="shape">
            <div class="heading">Оператор СУО QueueTS</div>
            <div class="row">
                {{ OperatorsForm }}
                <div class="operator-label">В очереди {{total_tickets}} посетителей</div>
                <div class="operator-div-button"><button class="operator-button" name="button_invited">Пригласить посетителя</button></div>
            </div>
            <div class="row">
                <div class="operator-label">Приглашен посетитель с талоном {{invited_ticket}}</div>
                <div class="operator-div-button"><button class="operator-button" name="button_serviced">Работать с посетителем</button></div>
                <div class="operator-end"></div>
            </div>
        </div>
    </div>
    <form>
</body>
</html>

queue_app/templates/queue_app/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link type="text/css" href="{% static 'queue_app/css/styles.css' %}" rel="stylesheet" />
    <meta charset="UTF-8">
    <title>Регистрация</title>
</head>
<body>
<div class="in-center-page">
<form action="{% url 'queue_app:registration' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div>
        <div class="registration-text">Для регистрации коснитесь кнопки</div>
        <div class="registration-div-button">
            <button type="submit" class="registration-button">РЕГИСТРАЦИЯ</button>
        </div>
    </div>
</form>
</div>
</body>
</html>

queue_app/templates/queue_app/screen.html

<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link type="text/css" href="{% static 'queue_app/css/styles.css' %}" rel="stylesheet" />
    <meta charset="UTF-8">
    <title>Главный экран</title>
    <meta http-equiv="refresh" content="2">
    <style>
         body {
           background-image: url("{% static 'queue_app/images/background.jpg' %}");
           background-size: cover;
         }
         table, tr, td {
             border-spacing: 8px;
             }
    </style>
</head>
<body>
  <div id="backdrop" style="height: {{ opacity_on_screen }}px;"></div>
  <div id="curtain">
      <table>
          <tr style="font-size: 30px">
              <td>№</td>
              <td>ТАЛОН</td>
              <td>ПРИГЛАШЕНИЕ</td>
          </tr>
          {% for p in list_for_screen %}
          <tr>
              <td align="center" style="font-size: 40px">{{forloop.counter}}.</td>
              <td align="center" style="font-weight: bold; font-size: 80px">{{p.ticket}}</td>
              <td align="left" style="font-size: 34px">
                  {% if forloop.counter == 1 %}
                  &nbsp;&nbsp;{{ invited_on_screen }}
                      <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ invited_on_screen2 }}
                  {% endif %}
              </td>
          </tr>
          {% endfor %}
      </table>
      </div>
      {% if gong == 1 %}
          <audio autoplay src="{% static 'queue_app/audio/gong.mp3' %}"></audio>
      {% endif %}
</body>
</html>

queue_app/templates/queue_app/ticket.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link type="text/css" href="{% static 'queue_app/css/styles.css' %}" rel="stylesheet" />
    <meta charset="UTF-8">
    <title>Талон</title>
    <script>
       setTimeout(function(){
            window.location.href = '/queue_app/registration/';
         }, 5000);
   </script>
</head>
<body>
<div class="in-center-page">
    <div class="ticket">
        <div class="ticket-footer">Талон посетителя</div>
        <div class="ticket-number"><p><h1>{{posts.ticket}}</h1></p></div>
        <div class="ticket-footer">
            <div>{{posts.data_reg}}</div>
            <div class="spacing"></div>
            <div>{{posts.time_reg}}</div>
        </div>
    </div>
</div>
</body>
</html>